USE BibliotecaIM253E07;
GO

CREATE TABLE [IM253E03Libro] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Autor] NVARCHAR(100) NOT NULL,
    [Editorial] NVARCHAR(100) NULL,
    [ISBN] NVARCHAR(50) NOT NULL,
    [Foto] NVARCHAR(MAX) NULL
);

CREATE TABLE [IM253E03Usuario] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Nombre] NVARCHAR(256) NOT NULL,
    [Direccion] NVARCHAR(200) NULL,
    [Telefono] NVARCHAR(50) NOT NULL,
    [Correo] NVARCHAR(100) NOT NULL
);

CREATE TABLE [IM253E03Prestamos] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [UsuarioId] UNIQUEIDENTIFIER NOT NULL,
    [LibroId] UNIQUEIDENTIFIER NOT NULL,
    [FechaPrestamo] SMALLDATETIME NOT NULL,
    [FechaDevolucion] SMALLDATETIME NULL,
    FOREIGN KEY ([UsuarioId]) REFERENCES [IM253E03Usuario]([Id]),
    FOREIGN KEY ([LibroId]) REFERENCES [IM253E03Libro]([Id])
);
